<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>2.1 - determine resident state with IT201</name>
  <uuid>046aea04-98ba-4788-a30c-988068d50e6d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if 
 decision is not null and IT201 is not null
then 
 set the computed of the R_CR_LMT_AMT of decision to the computed of the FEDADJ_AMT of IT201 ; 

    ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
