<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Household Gross Income</name>
  <uuid>643b9e97-7797-45de-b0ff-b96f9436c90b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set
	the value of the R_GRSS_INC_R_AMT of decision to round( max ( max ( the claimed of the R_GRSS_INC_R_AMT,the TEMP_FAGI of decision), 0) , 0);

    ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
