<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>NYS Resident</name>
  <uuid>899ccc30-5e70-41fc-9504-adc9d09ec508</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[If 
	IT201 is defined 
	then 
    	set the value of the R_RSDT_IND of decision to Standard ( 1 ) ; 
        set the TEMP_FAGI of decision to the value of the FEDAGI_RCOMP_AMT of IT201 ;
        
    ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
