<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>RAM 100022</name>
  <uuid>7e172afc-ca84-41ca-996b-099fa8e0b4ab</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the TEMP_CR_DENIED_IND of decision is not Present
	and the value of the R_GRSS_INC_R_AMT of 'input form' >0 then
	set the TEMP_LINE18 of decision to the value of the 
    R_GRSS_INC_R_AMT of 'input form' 
    * the RPTC_RATE of 'reference data';
else
	set the TEMP_LINE18 of decision to 0;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
