<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>RAM# 110342</name>
  <uuid>95e3089e-1a0e-458a-8cbe-230800a8a1c8</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the TEMP_CR_DENIED_IND of decision is Absent then
	 lookup RPTC from 'reference data' for $ the value of the R_GRSS_INC_R_AMT of 'input form' ; 
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
