<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>229 Accumulate Rule</name>
  <uuid>fe58adb3-e918-4ec1-ba96-9f6c2d89537f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the claimed of the RPTR_QRPT_PD_AMT of 'input form' > 0 then 
	set the value of the RPTR_QRPT_PD_AMT of decision to 0;
    for each QRPT Row in the QRPT_ROWs of 'input form' : 
    	- set the value of the RPTR_QRPT_PD_AMT of decision to 
        the value of the RPTR_QRPT_PD_AMT of decision +
        ((the RP_TX_PD_AMT of this QRPT Row - (the PI_PD_RES_AMT of this QRPT Row
        + the STAR_CR_SCH_TX_AMT of this QRPT Row)) * the ALLOC_PCT of this QRPT Row );]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
