<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>RAM 114455</name>
  <uuid>b696ab3b-7378-49d8-8436-76382326de83</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the claimed of the RPTR_QRPT_PD_AMT of 'input form' > 300 then 
	set the value of the RPTR_QRPT_PD_AMT of decision to 600;
else
	set the value of the RPTR_QRPT_PD_AMT of decision to 100;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
