<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>new rule</name>
  <uuid>5bf67310-9cdb-4cbb-b73d-f32521dad252</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[print "new rule";]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
